# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 12:30
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('uri', models.URLField(default=app.models._generate_unique_uri)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ChatSessionMember',
            new_name='ChatMember',
        ),
        migrations.RenameModel(
            old_name='ChatSessionMessage',
            new_name='ChatMessage',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatmember',
            name='chat_session',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='app.Chat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='app.Chat'),
            preserve_default=False,
        ),
    ]
